### PR TITLE
Microscape embed

### PR DESCRIPTION
**Pull request by JPFrancis**
Microscape embed pull request

## Current situation
Microscape iframe has been embedded as a popup window in the dataset.html page

## Release Notes 
Up to date with master and should not be a breaking change although it has yet to be tested with VMR server hookups.

## Documentation
See main.js "threeDOverlay" functions

## Testing
Open the database and click on the microscape button for any project

### CODE REVIEW

**Comment by ktbolt** [comment]
@JPFrancis  I don't see an Issue justifying this added functionality. What is this all about?

**Comment by lucapegolotti** [comment]
@ktbolt, you're right, sorry. We've been working for a few months with [Microscape](https://www.microscape.xyz) and Kitware to develop a custom 3D viewer to embed in the VMR website when browsing through the models. Alison is aware of this-in fact, we've set up a contract to be able to collaborate with Microscape and Kitware. This PR embeds the 3D viewer into the VMR website. I will deploy the website with github pages before merging it to tetra so we can show how it works to Alison, and then once we get the green light move it to the vascularmodel.com. I will create a separate issue and link it to this PR.

**Comment by ktbolt** [comment]
@lucapegolotti Very good!

**Comment by lucapegolotti** [comment]
A preview of the new version of the website can be seen here: https://jpfrancis.github.io/vascularmodel/dataset.html

@ktbolt, what do you think about it? You can click on any of the models that have a Microscape logo below the checkbox to open the 3D viewer.

**Comment by ktbolt** [comment]
@lucapegolotti The visualization looks OK, nice to provide an anatomical context for the model I suppose, although the model context is not that apparent.

I think the icon that opens the visualization should be moved to the upper right. The icon should also be changed to something more descriptive rather than what looks to me like a picture of the endoplasmic reticulum. 

The visualization window could have a better description than just `Here is the 3D visualization.`, maybe something like `Volume rendering of image 0086_H_PUM_PAH`.

Is it possible to include some control over the rendering like data mapping ?

**Comment by alisonmarsden** [comment]
This looks good to me.   I see you’ve made the changes that Dave suggested.   I’m in favor of merging in.   This worked out nicely!


From: Dave Parker ***@***.***>
Date: Monday, November 27, 2023 at 10:42 AM
To: SimVascular/vascularmodel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [SimVascular/vascularmodel] Microscape embed (PR #3)

@lucapegolotti<https://github.com/lucapegolotti> The visualization looks OK, nice to provide an anatomical context for the model I suppose, although the model context is not that apparent.

I think the icon that opens the visualization should be moved to the upper right. The icon should also be changed to something more descriptive rather than what looks to me like a picture of the endoplasmic reticulum.

The visualization window could have a better description than just Here is the 3D visualization., maybe something like Volume rendering of image 0086_H_PUM_PAH.

Is it possible to include some control over the rendering like data mapping ?

**Pull request merged**
